"use client";
import {useEffect,useMemo,useState} from "react";

const admissionSteps=["Verifică locurile vacante actualizate","Intră pe platforma admitere.pub.ro","Alege Pitești și Licență 2026 P.I Dosar","Completează datele și mediile","Alege programul și forma de finanțare","Achită taxa și încarcă documentele","Urmărește rezultatele și înmatriculează-te în termen"];
const sessions=[
 {id:"III.1",period:"6–7 august",signup:"6 august · 09:00–16:00",result:"6 august · 18:00",enroll:"7 august · 09:00–14:00",end:"2026-08-07T16:00:00",note:"Înscriere online sau fizic, sala S121"},
 {id:"III.2",period:"8–27 august",signup:"8–26 august · până la 16:00",result:"26 august · 18:00",enroll:"27 august · 09:00–16:00",end:"2026-08-27T17:00:00",note:"Înscriere online"},
 {id:"III.3",period:"28 august–12 septembrie",signup:"28 august–10 septembrie · până la 16:00",result:"10 septembrie · 20:00",enroll:"11–12 septembrie · până la 13:00",end:"2026-09-12T19:00:00",note:"Înscriere online"},
 {id:"III.5",period:"10–13 septembrie",signup:"10–12 septembrie · până la 16:00",result:"12 septembrie · 19:00",enroll:"13 septembrie · 09:00–12:00",end:"2026-09-13T16:00:00",note:"Etapă suplimentară, înscriere online"}
];
const requiredDocs=["Carte de identitate","Certificat de naștere","Diploma de Bacalaureat și foaia matricolă","Adeverință medicală","Dovada achitării taxei de înscriere","Cerere de înscriere descărcată din platformă și semnată","Declarație pe propria răspundere descărcată din platformă și semnată"];

export default function Page(){
 const [menu,setMenu]=useState(false),[done,setDone]=useState<boolean[]>(Array(7).fill(false)),[docDone,setDocDone]=useState<boolean[]>(Array(requiredDocs.length).fill(false));
 useEffect(()=>{try{const d=localStorage.getItem("dmi-progress-v3"),docs=localStorage.getItem("dmi-documents-v3");if(d)setDone(JSON.parse(d));if(docs)setDocDone(JSON.parse(docs))}catch{}},[]);
 useEffect(()=>{localStorage.setItem("dmi-progress-v3",JSON.stringify(done));localStorage.setItem("dmi-documents-v3",JSON.stringify(docDone))},[done,docDone]);
 const now=new Date(),start=new Date("2026-08-06T09:00:00"),finalEnd=new Date("2026-09-13T16:00:00");
 const activeSession=sessions.find(s=>now<=new Date(s.end)) || sessions[sessions.length-1];
 const urgency=useMemo(()=>now<start?{n:Math.max(0,Math.ceil((start.getTime()-now.getTime())/86400000)),label:"zile până la deschiderea Sesiunii III.1",state:"SESIUNEA III ÎNCEPE CURÂND"}:now<=finalEnd?{n:null,label:`Etapa ${activeSession.id} · ${activeSession.period}`,state:"SESIUNEA III · ADMITERE COMPLETARE"}:{n:null,label:"Sesiunea III s-a încheiat",state:"ADMITERE 2026 · SESIUNE ÎNCHEIATĂ"},[now.getTime(),activeSession.id]);
 const progress=Math.round(done.filter(Boolean).length/done.length*100);
 return <div className="shell"><aside className={menu?"open":""}><a className="brand" href="#top"><span>DMI</span><div><b>Admitere 2026</b><small>Informatică · Matematică</small></div></a><nav>{[["▦","Dashboard","top"],["!","Calendar sesiuni","session"],["✓","Pașii mei","steps"],["▤","Documente","documents"],["◇","Triada Fa–Do–Fi","triad"],["∑","Calculul mediei","calculator"],["◎","Locuri disponibile","seats"],["◫","Programe","programs"],["✦","Viața la DMI","benefits"],["⌖","Campus","campus"]].map(x=><a href={`#${x[2]}`} key={x[1]} onClick={()=>setMenu(false)}><i>{x[0]}</i>{x[1]}</a>)}</nav><div className="sideSocial"><small>URMĂREȘTE DMI</small><b>Noutăți, activități și viața de student</b><a href="https://linktr.ee/dmiupit" target="_blank" rel="noreferrer">Toate rețelele sociale ↗</a></div></aside>
 <main id="top"><header><button onClick={()=>setMenu(!menu)} aria-label="Meniu">☰</button><div><b>Dashboard de orientare în admitere</b><small>FȘEFI · Centrul Universitar Pitești</small></div><a href="https://admitere.pub.ro/Admitere/site/alegeCentru?idCentru=2" target="_blank" rel="noreferrer">Înscrie-te acum ↗</a></header><RightRail/><div className="content withRail">

 <section className="urgentHero third"><div><span className="live"><i/> {urgency.state}</span><h1>Sesiunea III de admitere</h1><p>6 august–13 septembrie · admitere pe bază de dosar pentru Informatică și Matematică</p><a href="https://admitere.pub.ro/Admitere/site/alegeCentru?idCentru=2" target="_blank" rel="noreferrer">Înscrie-te pentru Centrul Pitești ↗</a></div><div className="countdown">{urgency.n!==null&&<b>{urgency.n}</b>}<span>{urgency.label}</span><small>Locurile vacante se actualizează după fiecare etapă.</small></div></section>

 <section className="stats"><article className="hot"><small>LOCURI VACANTE · SURSĂ OFICIALĂ</small><b>Actualizate</b><p>Numărul locurilor se modifică după fiecare etapă.</p><a href="https://upit.ro/ro/academia-reorganizata/facultatea-de-stiinte-educatie-fizica-si-informatica/admitere-fsefi" target="_blank" rel="noreferrer">Verifică locurile disponibile ↗</a></article><article><small>PROGRESUL TĂU</small><b>{progress}%</b><div className="progress"><i style={{width:`${progress}%`}}/></div><p>{done.filter(Boolean).length} din {done.length} pași parcurși</p></article><article><small>ETAPA URMĂTOARE / ACTIVĂ</small><b>{activeSession.id}</b><p>{activeSession.signup}</p><a href="#session">Vezi toate etapele →</a></article></section>

 <section className="panel seatPanel" id="seats"><div className="title"><div><span>VERIFICARE ÎNAINTE DE ÎNSCRIERE</span><h2>Locuri vacante în Sesiunea III</h2></div><strong className="pulse">● DINAMIC</strong></div><div className="vacantPrograms"><article><i>&lt;/&gt;</i><div><h3>Informatică</h3><p>Admitere pe bază de dosar, în limita locurilor vacante.</p></div></article><article><i>Σ</i><div><h3>Matematică</h3><p>Admitere pe bază de dosar, în limita locurilor vacante.</p></div></article></div><a className="officialCta" href="https://upit.ro/ro/academia-reorganizata/facultatea-de-stiinte-educatie-fizica-si-informatica/admitere-fsefi" target="_blank" rel="noreferrer">Consultă situația oficială a locurilor vacante ↗</a><p className="note">PDF-ul din 31.07.2026 nu precizează numărul locurilor. Pagina facultății se actualizează după fiecare etapă de admitere.</p></section>

 <section className="panel" id="session"><div className="title"><div><span>CRONOLOGIA ADMITERII · INFORMATICĂ ȘI MATEMATICĂ</span><h2>Urmărește traseul Sesiunii III</h2><p>Parcurge etapele în ordine și verifică termenul de înmatriculare după fiecare rezultat.</p></div><em>6 august–13 septembrie</em></div><div className="timelineLegend"><span><i className="legendPast"/>Încheiată</span><span><i className="legendCurrent"/>Activă / următoare</span><span><i className="legendFuture"/>Urmează</span></div><div className="sessionCards">{sessions.map((s,i)=>{const past=now>new Date(s.end),current=s.id===activeSession.id&&!past;return <article className={current?"current":past?"past":"future"} key={s.id}><header><i>{past?"✓":i+1}</i><div><b>Sesiunea {s.id}</b><span>{s.period}</span></div><em>{current?"URMĂTOAREA / ACTIVĂ":past?"ÎNCHEIATĂ":"URMEAZĂ"}</em></header><dl><div><dt>Înscrieri</dt><dd>{s.signup}</dd></div><div><dt>Rezultate admiși</dt><dd>{s.result}</dd></div><div><dt>Înmatriculări</dt><dd>{s.enroll}</dd></div></dl><p>{s.note}</p></article>})}</div><div className="calendarNote"><b>Important:</b> Sesiunea III.4 este pentru admiterea vocațională și nu se aplică programelor Informatică și Matematică. Etapele „+” permit înmatricularea directă, în ordinea mediilor, pentru candidații cu barem îndeplinit, pe locurile rămase.</div></section>

 <section className="panel" id="steps"><div className="title"><div><span>CHECKLIST INTERACTIV</span><h2>Pașii tăi pentru admitere</h2></div><div className="miniProgress"><b>{progress}%</b><span>{done.filter(Boolean)}/{done.length} finalizați</span></div></div><div className="steps">{admissionSteps.map((s,i)=><button className={done[i]?"done":""} onClick={()=>setDone(done.map((v,j)=>j===i?!v:v))} key={s}><i>{done[i]?"✓":i+1}</i><span>{s}</span><em>{done[i]?"Finalizat":"Apasă când ai terminat"}</em></button>)}</div><button className="reset" onClick={()=>setDone(Array(7).fill(false))}>Resetează progresul</button></section>

 <section className="panel" id="documents"><div className="title"><div><span>CHECKLIST DOCUMENTE · SESIUNEA III</span><h2>Pregătește dosarul</h2></div><div className="miniProgress"><b>{Math.round(docDone.filter(Boolean).length/docDone.length*100)}%</b><span>{docDone.filter(Boolean).length}/{docDone.length} pregătite</span></div></div><div className="documents">{requiredDocs.map((d,i)=><button className={docDone[i]?"ready":""} onClick={()=>setDocDone(docDone.map((v,j)=>j===i?!v:v))} key={d}><i>{docDone[i]?"✓":"□"}</i><span>{d}</span><em>{docDone[i]?"Pregătit":"De pregătit"}</em></button>)}</div><div className="feeNote"><b>Taxa de înscriere: 125 lei.</b><span>Candidații cu barem îndeplinit în Sesiunile I și II achită 50 lei. Cererea și declarația se descarcă din platformă, se semnează și se încarcă din nou.</span></div><p className="note">Înmatricularea se face la sediul FȘEFI, Corp S, sala S009, Str. Târgul din Vale nr. 1, Pitești.</p></section>

 <section className="triad" id="triad"><div className="sectionTitle"><span>ALEGE CORECT PE PLATFORMĂ</span><h2>Triada Fa–Do–Fi</h2><p>Codul opțiunii tale combină facultatea, domeniul și forma de finanțare.</p></div><div className="triadFlow"><article><i>Fa</i><small>FACULTATE</small><h3>FȘEFI</h3><p>Facultatea de Științe, Educație Fizică și Informatică</p></article><b>+</b><article><i>Do</i><small>DOMENIU</small><h3>Inf / Mat</h3><p>Informatică sau Matematică</p></article><b>+</b><article><i>Fi</i><small>FINANȚARE</small><h3>B / Tx</h3><p>Buget sau Taxă</p></article><b>=</b><div className="triadResult"><small>EXEMPLU</small><strong>FȘEFI–Inf–B</strong><span>Informatică · loc bugetat</span></div></div><div className="triadTip">Pe platformă selectează <b>Pitești</b>, apoi <b>Licență 2026 P.I Dosar</b>. Verifică toate cele trei componente înainte de plată.</div></section>

 <AdmissionCalculator/>

 <section id="programs" className="programSection"><div className="sectionTitle"><span>PROGRAME DE LICENȚĂ</span><h2>Alege specializarea potrivită</h2></div><div className="programGrid"><Program type="info" icon="</>" title="Informatică" text="Pentru cei care vor să înțeleagă și să construiască sisteme software, să lucreze cu date și să transforme ideile în aplicații." subjects={["Programare și algoritmi","Structuri de date","Baze de date","Programare orientată pe obiecte","Sisteme de operare","Inteligență artificială"]}/><Program type="math" icon="Σ" title="Matematică" text="Pentru cei atrași de raționament riguros, modelare și structurile care stau la baza științei, tehnologiei și analizei datelor." subjects={["Analiză matematică","Algebră liniară","Geometrie","Ecuații diferențiale","Probabilități și statistică","Modelare matematică"]}/></div><p className="note">Disciplinele sunt exemple orientative de arii studiate. Planul oficial de învățământ publicat de facultate prevalează.</p></section>

 <section className="experience" id="benefits"><div className="sectionTitle"><span>MAI MULT DECÂT CURSURI</span><h2>Beneficii și experiențe</h2></div><div className="benefitGrid">{[["✈","Erasmus+","Mobilități internaționale și proiecte în care descoperi alte medii academice."],["▣","Practică","Aplici ceea ce înveți în contexte concrete și îți dezvolți portofoliul."],["↗","Internship","Explorezi roluri profesionale și interacționezi cu piața muncii prin oportunități disponibile."],["⚑","Proiecte & concursuri","Lucrezi în echipă, îți testezi ideile și participi la activități academice."],["♥","Comunitate","Beneficiezi de sprijinul profesorilor și evoluezi într-un centru universitar accesibil."],["★","Voluntariat & Work & Travel","Îți completezi experiența de student cu activități extracurriculare diverse."]].map(x=><article key={x[1]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>

 <section className="david"><div><span>DMI · BOOT YOUR FUTURE</span><h2>Fii mintea din spatele inteligenței.</h2><p>Instrumentele se schimbă. Gândirea pe care o construiești rămâne.</p><a href="https://admitere.pub.ro/Admitere/site/alegeCentru?idCentru=2" target="_blank" rel="noreferrer">Înscrie-te la DMI ↗</a></div><img src="/david-hero.png" alt="Interpretare digitală a statuii David"/></section>

 <section className="campus" id="campus"><div className="map"><iframe title="Harta campusului Centrului Universitar Pitești" src="https://www.google.com/maps?q=Strada+Targu+din+Vale+1+Pitesti&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div><div className="campusInfo"><span>CAMPUS & CONTACT</span><h2>Ne găsești în Pitești</h2><p>Secretariat FȘEFI<br/><b>Str. Târgul din Vale nr. 1, Corp S, Pitești</b></p><p>Telefon: <b>0348 453 260</b></p><a href="https://www.google.com/maps/search/?api=1&query=Strada+Targu+din+Vale+1+Pitesti" target="_blank" rel="noreferrer">Deschide traseul ↗</a><a className="social" href="https://linktr.ee/dmiupit" target="_blank" rel="noreferrer"><small>SOCIAL MEDIA DMI</small><b>linktr.ee/dmiupit</b><span>Facebook · Instagram · TikTok · LinkedIn ↗</span></a></div></section>
 <footer><b>DMI · Centrul Universitar Pitești</b><span>Informațiile oficiale și platforma admitere.pub.ro prevalează.</span></footer>
 </div></main></div>}

function Program({type,icon,title,text,subjects}:{type:string,icon:string,title:string,text:string,subjects:string[]}){return <article className={type}><div className="programHead"><i>{icon}</i><div><small>PROGRAM DE LICENȚĂ</small><h3>{title}</h3></div></div><p>{text}</p><b>Exemple de discipline</b><ul>{subjects.map(s=><li key={s}>{s}</li>)}</ul><a href="http://dmi.upit.ro/" target="_blank" rel="noreferrer">Descoperă programul ↗</a></article>}

function AdmissionCalculator(){const [nc1,setNc1]=useState(""),[nc2,setNc2]=useState(""),[nb,setNb]=useState("");const value=(x:string)=>Number(x.replace(",","."));const valid=[nc1,nc2,nb].every(x=>x!==""&&!isNaN(value(x))&&value(x)>=1&&value(x)<=10);const result=valid?(((value(nc1)+value(nc2))/2)*.8+value(nb)*.2).toFixed(2):"—";return <section className="calculator" id="calculator"><div className="calcIntro"><span>CALCULATOR ORIENTATIV</span><h2>Calculează media de admitere</h2><p>Completează cele trei valori folosind formula din materialul Admitere 2026.</p><div className="calcFormula">MA = ((NC1 + NC2) / 2) × 0,80 + NB × 0,20</div></div><div className="calcFields"><label><b>NC1</b><span>Media anuală la Matematică</span><input value={nc1} onChange={e=>setNc1(e.target.value)} inputMode="decimal" placeholder="ex. 9,00"/></label><label><b>NC2</b><span>Media anuală la disciplina aleasă</span><input value={nc2} onChange={e=>setNc2(e.target.value)} inputMode="decimal" placeholder="ex. 10,00"/></label><label><b>NB</b><span>Punctaj concursuri / olimpiade sau media BAC</span><input value={nb} onChange={e=>setNb(e.target.value)} inputMode="decimal" placeholder="ex. 9,20"/></label></div><div className="calcResult"><small>MEDIA ESTIMATĂ</small><strong>{result}</strong><span>din 10</span><p>Rezultatul este orientativ. Metodologia oficială prevalează.</p></div></section>}

function RightRail(){const [topic,setTopic]=useState("calendar"),[message,setMessage]=useState("");const answers:{[k:string]:string}={calendar:"Sesiunea III are etape între 6 august și 13 septembrie. Pentru Informatică și Matematică urmărește III.1, III.2, III.3 și III.5.",documents:"Dosarul include CI, certificat de naștere, diploma de Bacalaureat cu foaia matricolă, adeverință medicală, dovada taxei, cererea și declarația semnate.",average:"Media se calculează pe baza probelor P1, P2 și P3 prevăzute pentru Sesiunea II în regulamentul oficial.",places:"Locurile vacante sunt publicate de facultate și se actualizează după fiecare etapă; nu pot fi editate din acest site."};return <aside className="rightRail">
 <section className="railCard"><div className="railTitle"><b>SESIUNEA III · 2026</b><span>Admitere completare</span></div><div className="railDates"><article><b>III.1</b><span>6–7 aug.</span></article><article><b>III.2</b><span>8–27 aug.</span></article><article><b>III.3</b><span>28 aug.–12 sept.</span></article><article><b>III.5</b><span>10–13 sept.</span></article></div><p><i/> Pentru Informatică și Matematică · admitere pe bază de dosar</p></section>
 <section className="railCard socialHub"><span>LINKURI & SOCIAL</span><div className="socialPlatforms"><a href="https://linktr.ee/dmiupit" target="_blank" rel="noreferrer">Linktree</a><a href="https://www.facebook.com/MATINF.UPIT" target="_blank" rel="noreferrer">Facebook</a><a href="https://www.instagram.com/dmi.fsefi.cupit" target="_blank" rel="noreferrer">Instagram</a><a href="https://www.tiktok.com/@cup_fsefi_mate_info" target="_blank" rel="noreferrer">TikTok</a><a href="https://www.linkedin.com/company/108330858" target="_blank" rel="noreferrer">LinkedIn</a></div><a className="utilityLink" href="https://admitere.pub.ro/Admitere/site/alegeCentru?idCentru=2" target="_blank" rel="noreferrer">↗ Platforma de admitere Pitești</a><a className="utilityLink" href="http://dmi.upit.ro/" target="_blank" rel="noreferrer">↗ Website DMI</a><a className="utilityLink" href="mailto:dmiupit@yahoo.com">✉ dmiupit@yahoo.com</a></section>
 <section className="railCard opportunities"><span>CONCURSURI & ACTIVITĂȚI</span><article><i>⌁</i><div><b>Programming Day for High School</b><small>Concurs DMI pentru elevi pasionați de programare.</small></div></article><article><i>✈</i><div><b>Erasmus+</b><small>Mobilități și experiențe academice internaționale.</small></div></article><article><i>↗</i><div><b>Practică & internship</b><small>Experiență profesională și conectare cu piața muncii.</small></div></article><article><i>♥</i><div><b>Voluntariat & proiecte</b><small>Activități extracurriculare și lucru în echipă.</small></div></article></section>
 <section className="railCard partners"><span>EXEMPLE DE PARTENERI</span><h3>Companii și organizații</h3><p>Exemple de companii cu care DMI a colaborat în activități profesionale și academice:</p>{[["LD","LISA DRÄXLMAIER Pitești"],["TX","Textron"],["PI","ProdInf"],["EN","Endava"],["RW","Roweb"]].map(x=><div className="partnerLogo" key={x[1]}><i>{x[0]}</i><b>{x[1]}</b></div>)}</section>
 <section className="railCard helper"><span>ASISTENT DE ORIENTARE</span><h3>Cu ce te putem ajuta?</h3><div className="topicButtons">{[["calendar","Calendar"],["documents","Documente"],["average","Medie"],["places","Locuri"]].map(x=><button className={topic===x[0]?"active":""} onClick={()=>setTopic(x[0])} key={x[0]}>{x[1]}</button>)}</div><p>{answers[topic]}</p><label>Întrebare suplimentară<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Scrie întrebarea ta..."/></label><a className={message?"enabled":""} href={message?`mailto:dmiupit@yahoo.com?subject=${encodeURIComponent("Întrebare admitere DMI 2026")}&body=${encodeURIComponent(message)}`:undefined}>Trimite întrebarea prin e-mail ↗</a><small>Acesta este un ghid local, nu un agent AI conectat și nu trimite notificări automat.</small></section>
 </aside>}
