"use client";
import {useEffect,useMemo,useState} from "react";
import "./styles.css";

const admissionSteps=["Intră pe platforma admitere.pub.ro","Alege Pitești și Licență 2026 P.I Dosar","Completează datele și mediile","Alege programul și forma de finanțare","Achită taxa și încarcă documentele","Finalizează înscrierea","Urmărește rezultatele și confirmă locul"];
const dates=[{d:"20 iul.",t:"Deschidere înscrieri online",date:"2026-07-20"},{d:"29 iul. · 12:00",t:"Închidere înscrieri online",date:"2026-07-29"},{d:"30 iul. · 16:00",t:"Închidere înscriere fizică",date:"2026-07-30"},{d:"31 iul. · 12:00",t:"Rezultate preliminare",date:"2026-07-31"},{d:"1 aug. · 18:00",t:"Rezultate finale",date:"2026-08-01"},{d:"1–2 aug.",t:"Validare și înmatriculare",date:"2026-08-02"}];
const requiredDocs=["Certificat de naștere","Act de identitate","Fotografie color tip CI","Foaie matricolă","Diplomă de Bacalaureat (Sesiunea II)","Cerere de înscriere semnată","Declarație pe propria răspundere","Adeverință medicală","Dovada achitării taxei","Documente concursuri / olimpiade, dacă este cazul"];

export default function Page(){
 const [menu,setMenu]=useState(false),[done,setDone]=useState<boolean[]>(Array(7).fill(false)),[docDone,setDocDone]=useState<boolean[]>(Array(requiredDocs.length).fill(false)),[edit,setEdit]=useState(false),[seats,setSeats]=useState({ib:13,it:94,mb:9,mt:5});
 useEffect(()=>{try{const d=localStorage.getItem("dmi-progress-v2"),docs=localStorage.getItem("dmi-documents");if(d)setDone(JSON.parse(d));if(docs)setDocDone(JSON.parse(docs))}catch{}},[]);
 useEffect(()=>{localStorage.setItem("dmi-progress-v2",JSON.stringify(done));localStorage.setItem("dmi-documents",JSON.stringify(docDone))},[done,docDone]);
 const today=new Date();today.setHours(0,0,0,0);const start=new Date("2026-07-20T00:00:00"),end=new Date("2026-07-30T23:59:59");
 const urgency=useMemo(()=>today<start?{n:Math.ceil((start.getTime()-today.getTime())/86400000),label:"zile până la deschiderea Sesiunii II",state:"SESIUNEA II ÎNCEPE CURÂND",third:false}:today<=end?{n:Math.max(0,Math.ceil((end.getTime()-today.getTime())/86400000)),label:"zile până la închiderea Sesiunii II",state:"SESIUNEA II · ÎNSCRIERI DESCHISE",third:false}:{n:null,label:"Calendarul va fi publicat în funcție de locurile rămase",state:"SESIUNEA III · COMPLETARE",third:true},[]);
 const progress=Math.round(done.filter(Boolean).length/done.length*100),total=Object.values(seats).reduce((a,b)=>a+b,0);
 const setSeat=(k:keyof typeof seats,v:string)=>setSeats({...seats,[k]:Math.max(0,Number(v)||0)});
 return <div className="shell"><aside className={menu?"open":""}><a className="brand" href="#top"><span>DMI</span><div><b>Admitere 2026</b><small>Informatică · Matematică</small></div></a><nav>{[["▦","Dashboard","top"],["!","Calendar sesiuni","session"],["✓","Pașii mei","steps"],["▤","Documente","documents"],["◇","Triada Fa–Do–Fi","triad"],["∑","Calculul mediei","calculator"],["◎","Locuri disponibile","seats"],["◫","Programe","programs"],["✦","Viața la DMI","benefits"],["⌖","Campus","campus"]].map(x=><a href={`#${x[2]}`} key={x[1]} onClick={()=>setMenu(false)}><i>{x[0]}</i>{x[1]}</a>)}</nav><div className="sideSocial"><small>URMĂREȘTE DMI</small><b>Noutăți, activități și viața de student</b><a href="https://linktr.ee/dmiupit" target="_blank" rel="noreferrer">Toate rețelele sociale ↗</a></div></aside>
 <main id="top"><header><button onClick={()=>setMenu(!menu)} aria-label="Meniu">☰</button><div><b>Dashboard de orientare în admitere</b><small>FȘEFI · Centrul Universitar Pitești</small></div><a href="https://admitere.pub.ro/Admitere/site/alegeCentru?idCentru=2" target="_blank" rel="noreferrer">Înscrie-te acum ↗</a></header><RightRail today={today}/><div className="content withRail">

 <section className={`urgentHero ${urgency.third?"third":""}`}><div><span className="live"><i/> {urgency.state}</span><h1>{urgency.third?"Sesiunea III de completare":"Sesiunea II de admitere"}</h1><p>{urgency.third?"Se organizează numai în funcție de locurile rămase după primele două sesiuni.":"Online: 20–29 iulie, ora 12:00 · Fizic: 29–30 iulie, 08:00–16:00"}</p><a href="https://admitere.pub.ro/Admitere/site/alegeCentru?idCentru=2" target="_blank" rel="noreferrer">Verifică platforma pentru Pitești ↗</a></div><div className="countdown">{urgency.n!==null&&<b>{urgency.n}</b>}<span>{urgency.label}</span><small>{urgency.third?"Verifică locurile și anunțurile actualizate.":"Nu lăsa dosarul pentru ultima zi."}</small></div></section>

 <section className="stats"><article className="hot"><small>LOCURI SESIUNEA II · SURSĂ OFICIALĂ</small><b>{total}</b><p>{seats.ib+seats.mb} buget · {seats.it+seats.mt} taxă</p></article><article><small>PROGRESUL TĂU</small><b>{progress}%</b><div className="progress"><i style={{width:`${progress}%`}}/></div><p>{done.filter(Boolean).length} din {done.length} pași parcurși</p></article><article><small>URMĂTORUL TERMEN</small><b>29 iulie · 12:00</b><p>Închiderea înscrierilor online</p><a href="#session">Vezi cronologia →</a></article></section>

 <section className="panel seatPanel" id="seats"><div className="title"><div><span>ACTUALIZAT DIN PAGINA DMI</span><h2>Locuri disponibile în Sesiunea II</h2></div><strong className="pulse">● URGENT</strong></div><div className="seatPrograms"><Seat title="Informatică" icon="</>" budget={seats.ib} tax={seats.it} edit={edit} onBudget={v=>setSeat("ib",v)} onTax={v=>setSeat("it",v)}/><Seat title="Matematică" icon="Σ" budget={seats.mb} tax={seats.mt} edit={edit} onBudget={v=>setSeat("mb",v)} onTax={v=>setSeat("mt",v)}/></div><p className="note">Valorile pot fi modificate local. <a href="https://www.upit.ro/ro/academia-reorganizata/facultatea-de-stiinte-educatie-fizica-si-informatica/departamente-la-nivelul-facultatii-de-stiinte-educatie-fizica-si-informatica/departamentul-matematica-informatica2/admitere-matematica-informatica/admitere-licenta-dmi/sesiunea-ii-admitere-dmi" target="_blank" rel="noreferrer">Verifică și actualizează din sursa oficială DMI ↗</a></p></section>

 <section className="panel" id="session"><div className="title"><div><span>UNDE SUNTEM ACUM</span><h2>Cronologia Sesiunii II</h2></div><em>20 iulie – 2 august</em></div><div className="timeline">{dates.map((x,i)=>{const date=new Date(x.date+"T23:59:59"),isToday=today.toDateString()===new Date(x.date+"T00:00:00").toDateString(),past=today>date;return <article className={isToday?"current":past?"past":"future"} key={x.t}><i>{past?"✓":i+1}</i><b>{x.d}</b><span>{x.t}</span><em>{isToday?"ASTĂZI":past?"ÎNCHEIAT":"URMEAZĂ"}</em></article>})}</div></section>

 <section className="panel" id="steps"><div className="title"><div><span>CHECKLIST INTERACTIV</span><h2>Pașii tăi pentru admitere</h2></div><div className="miniProgress"><b>{progress}%</b><span>{done.filter(Boolean)}/{done.length} finalizați</span></div></div><div className="steps">{admissionSteps.map((s,i)=><button className={done[i]?"done":""} onClick={()=>setDone(done.map((v,j)=>j===i?!v:v))} key={s}><i>{done[i]?"✓":i+1}</i><span>{s}</span><em>{done[i]?"Finalizat":"Apasă când ai terminat"}</em></button>)}</div><button className="reset" onClick={()=>setDone(Array(7).fill(false))}>Resetează progresul</button></section>

 <section className="panel" id="documents"><div className="title"><div><span>CHECKLIST DOCUMENTE</span><h2>Pregătește dosarul</h2></div><div className="miniProgress"><b>{Math.round(docDone.filter(Boolean).length/docDone.length*100)}%</b><span>{docDone.filter(Boolean).length}/{docDone.length} pregătite</span></div></div><div className="documents">{requiredDocs.map((d,i)=><button className={docDone[i]?"ready":""} onClick={()=>setDocDone(docDone.map((v,j)=>j===i?!v:v))} key={d}><i>{docDone[i]?"✓":"□"}</i><span>{d}</span><em>{docDone[i]?"Pregătit":"De pregătit"}</em></button>)}</div><p className="note">Checklist orientativ pe baza materialului Admitere 2026. Verifică metodologia și cerințele afișate pe platformă înainte de finalizare.</p></section>

 <section className="triad" id="triad"><div className="sectionTitle"><span>ALEGE CORECT PE PLATFORMĂ</span><h2>Triada Fa–Do–Fi</h2><p>Codul opțiunii tale combină facultatea, domeniul și forma de finanțare.</p></div><div className="triadFlow"><article><i>Fa</i><small>FACULTATE</small><h3>FȘEFI</h3><p>Facultatea de Științe, Educație Fizică și Informatică</p></article><b>+</b><article><i>Do</i><small>DOMENIU</small><h3>Inf / Mat</h3><p>Informatică sau Matematică</p></article><b>+</b><article><i>Fi</i><small>FINANȚARE</small><h3>B / Tx</h3><p>Buget sau Taxă</p></article><b>=</b><div className="triadResult"><small>EXEMPLU</small><strong>FȘEFI–Inf–B</strong><span>Informatică · loc bugetat</span></div></div><div className="triadTip">Pe platformă selectează <b>Pitești</b>, apoi <b>Licență 2026 P.I Dosar</b>. Verifică toate cele trei componente înainte de plată.</div></section>

 <AdmissionCalculator/>

 <section id="programs" className="programSection"><div className="sectionTitle"><span>PROGRAME DE LICENȚĂ</span><h2>Alege specializarea potrivită</h2></div><div className="programGrid"><Program type="info" icon="</>" title="Informatică" text="Pentru cei care vor să înțeleagă și să construiască sisteme software, să lucreze cu date și să transforme ideile în aplicații." subjects={["Programare și algoritmi","Structuri de date","Baze de date","Programare orientată pe obiecte","Sisteme de operare","Inteligență artificială"]}/><Program type="math" icon="Σ" title="Matematică" text="Pentru cei atrași de raționament riguros, modelare și structurile care stau la baza științei, tehnologiei și analizei datelor." subjects={["Analiză matematică","Algebră liniară","Geometrie","Ecuații diferențiale","Probabilități și statistică","Modelare matematică"]}/></div><p className="note">Disciplinele sunt exemple orientative de arii studiate. Planul oficial de învățământ publicat de facultate prevalează.</p></section>

 <section className="experience" id="benefits"><div className="sectionTitle"><span>MAI MULT DECÂT CURSURI</span><h2>Beneficii și experiențe</h2></div><div className="benefitGrid">{[["✈","Erasmus+","Mobilități internaționale și proiecte în care descoperi alte medii academice."],["▣","Practică","Aplici ceea ce înveți în contexte concrete și îți dezvolți portofoliul."],["↗","Internship","Explorezi roluri profesionale și interacționezi cu piața muncii prin oportunități disponibile."],["⚑","Proiecte & concursuri","Lucrezi în echipă, îți testezi ideile și participi la activități academice."],["♥","Comunitate","Beneficiezi de sprijinul profesorilor și evoluezi într-un centru universitar accesibil."],["★","Voluntariat & Work & Travel","Îți completezi experiența de student cu activități extracurriculare diverse."]].map(x=><article key={x[1]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>

 <section className="david"><div><span>DMI · BOOT YOUR FUTURE</span><h2>Fii mintea din spatele inteligenței.</h2><p>Instrumentele se schimbă. Gândirea pe care o construiești rămâne.</p><a href="https://admitere.pub.ro/Admitere/site/alegeCentru?idCentru=2" target="_blank" rel="noreferrer">Înscrie-te la DMI ↗</a></div><img src={`${import.meta.env.BASE_URL}david-hero.png`} alt="Interpretare digitală a statuii David"/></section>

 <section className="campus" id="campus"><div className="map"><iframe title="Harta campusului Centrului Universitar Pitești" src="https://www.google.com/maps?q=Strada+Targu+din+Vale+1+Pitesti&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div><div className="campusInfo"><span>CAMPUS & CONTACT</span><h2>Ne găsești în Pitești</h2><p>Secretariat FȘEFI<br/><b>Str. Târgul din Vale nr. 1, Corp S, Pitești</b></p><p>Telefon: <b>0348 453 260</b></p><a href="https://www.google.com/maps/search/?api=1&query=Strada+Targu+din+Vale+1+Pitesti" target="_blank" rel="noreferrer">Deschide traseul ↗</a><a className="social" href="https://linktr.ee/dmiupit" target="_blank" rel="noreferrer"><small>SOCIAL MEDIA DMI</small><b>linktr.ee/dmiupit</b><span>Facebook · Instagram · TikTok · YouTube ↗</span></a></div></section>
 <footer><b>DMI · Centrul Universitar Pitești</b><span>Informațiile oficiale și platforma admitere.pub.ro prevalează.</span></footer>
 </div></main></div>}

function Seat({title,icon,budget,tax,edit,onBudget,onTax}:{title:string,icon:string,budget:number,tax:number,edit:boolean,onBudget:(v:string)=>void,onTax:(v:string)=>void}){return <article><div><i>{icon}</i><h3>{title}</h3><b>{budget+tax} locuri</b></div><label>BUGET {edit?<input type="number" value={budget} onChange={e=>onBudget(e.target.value)}/>:<strong>{budget}</strong>}</label><label>TAXĂ {edit?<input type="number" value={tax} onChange={e=>onTax(e.target.value)}/>:<strong>{tax}</strong>}</label></article>}
function Program({type,icon,title,text,subjects}:{type:string,icon:string,title:string,text:string,subjects:string[]}){return <article className={type}><div className="programHead"><i>{icon}</i><div><small>PROGRAM DE LICENȚĂ</small><h3>{title}</h3></div></div><p>{text}</p><b>Exemple de discipline</b><ul>{subjects.map(s=><li key={s}>{s}</li>)}</ul><a href="http://dmi.upit.ro/" target="_blank" rel="noreferrer">Descoperă programul ↗</a></article>}

function AdmissionCalculator(){const [nc1,setNc1]=useState(""),[nc2,setNc2]=useState(""),[nb,setNb]=useState("");const value=(x:string)=>Number(x.replace(",","."));const valid=[nc1,nc2,nb].every(x=>x!==""&&!isNaN(value(x))&&value(x)>=1&&value(x)<=10);const result=valid?(((value(nc1)+value(nc2))/2)*.8+value(nb)*.2).toFixed(2):"—";return <section className="calculator" id="calculator"><div className="calcIntro"><span>CALCULATOR ORIENTATIV</span><h2>Calculează media de admitere</h2><p>Completează cele trei valori folosind formula din materialul Admitere 2026.</p><div className="calcFormula">MA = ((NC1 + NC2) / 2) × 0,80 + NB × 0,20</div></div><div className="calcFields"><label><b>NC1</b><span>Media anuală la Matematică</span><input value={nc1} onChange={e=>setNc1(e.target.value)} inputMode="decimal" placeholder="ex. 9,00"/></label><label><b>NC2</b><span>Media anuală la disciplina aleasă</span><input value={nc2} onChange={e=>setNc2(e.target.value)} inputMode="decimal" placeholder="ex. 10,00"/></label><label><b>NB</b><span>Punctaj concursuri / olimpiade sau media BAC</span><input value={nb} onChange={e=>setNb(e.target.value)} inputMode="decimal" placeholder="ex. 9,20"/></label></div><div className="calcResult"><small>MEDIA ESTIMATĂ</small><strong>{result}</strong><span>din 10</span><p>Rezultatul este orientativ. Metodologia oficială prevalează.</p></div></section>}

function RightRail({today}:{today:Date}){const [topic,setTopic]=useState("calendar"),[message,setMessage]=useState("");const answers:{[k:string]:string}={calendar:"Sesiunea II: online 20–29 iulie, fizic 29–30 iulie. Sesiunea III depinde de locurile rămase.",documents:"Pentru Sesiunea II pregătește inclusiv Diploma de Bacalaureat. Lista completă este în checklist.",average:"Formula este MA = ((NC1 + NC2) / 2) × 0,80 + NB × 0,20.",places:"Locurile din dashboard pot fi actualizate manual. Confirmarea oficială rămâne pe platforma de admitere."};const days=[...Array(31)].map((_,i)=>i+1);return <aside className="rightRail">
 <section className="railCard"><div className="railTitle"><b>IULIE 2026</b><span>Sesiunea II</span></div><div className="week"><i>L</i><i>Ma</i><i>Mi</i><i>J</i><i>V</i><i>S</i><i>D</i></div><div className="month">{[...Array(2)].map((_,i)=><i key={`e${i}`}/>)}{days.map(d=><b className={`${d>=20&&d<=30?"range":""} ${today.getMonth()===6&&today.getDate()===d?"today":""}`} key={d}>{d}</b>)}</div><p><i/> 20–30 iulie · perioada Sesiunii II</p></section>
 <section className="railCard socialHub"><span>LINKURI & SOCIAL</span><div className="socialPlatforms"><a href="https://linktr.ee/dmiupit" target="_blank" rel="noreferrer">Linktree</a><a href="https://www.facebook.com/MATINF.UPIT" target="_blank" rel="noreferrer">Facebook</a><a href="https://www.instagram.com/dmi.fsefi.cupit" target="_blank" rel="noreferrer">Instagram</a><a href="https://www.tiktok.com/@cup_fsefi_mate_info" target="_blank" rel="noreferrer">TikTok</a><a href="https://www.linkedin.com/company/108330858" target="_blank" rel="noreferrer">LinkedIn</a></div><a className="utilityLink" href="https://admitere.pub.ro/Admitere/site/alegeCentru?idCentru=2" target="_blank" rel="noreferrer">↗ Platforma de admitere Pitești</a><a className="utilityLink" href="http://dmi.upit.ro/" target="_blank" rel="noreferrer">↗ Website DMI</a><a className="utilityLink" href="mailto:dmiupit@yahoo.com">✉ dmiupit@yahoo.com</a></section>
 <section className="railCard opportunities"><span>CONCURSURI & ACTIVITĂȚI</span><article><i>⌁</i><div><b>Programming Day for High School</b><small>Concurs DMI pentru elevi pasionați de programare.</small></div></article><article><i>✈</i><div><b>Erasmus+</b><small>Mobilități și experiențe academice internaționale.</small></div></article><article><i>↗</i><div><b>Practică & internship</b><small>Experiență profesională și conectare cu piața muncii.</small></div></article><article><i>♥</i><div><b>Voluntariat & proiecte</b><small>Activități extracurriculare și lucru în echipă.</small></div></article></section>
 <section className="railCard partners"><span>EXEMPLE DE PARTENERI</span><h3>Companii și organizații</h3><p>Exemple de companii cu care DMI a colaborat în activități profesionale și academice:</p>{[["LD","LISA DRÄXLMAIER Pitești"],["TX","Textron"],["PI","ProdInf"],["EN","Endava"],["RW","Roweb"]].map(x=><div className="partnerLogo" key={x[1]}><i>{x[0]}</i><b>{x[1]}</b></div>)}</section>
 <section className="railCard helper"><span>ASISTENT DE ORIENTARE</span><h3>Cu ce te putem ajuta?</h3><div className="topicButtons">{[["calendar","Calendar"],["documents","Documente"],["average","Medie"],["places","Locuri"]].map(x=><button className={topic===x[0]?"active":""} onClick={()=>setTopic(x[0])} key={x[0]}>{x[1]}</button>)}</div><p>{answers[topic]}</p><label>Întrebare suplimentară<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Scrie întrebarea ta..."/></label><a className={message?"enabled":""} href={message?`mailto:dmiupit@yahoo.com?subject=${encodeURIComponent("Întrebare admitere DMI 2026")}&body=${encodeURIComponent(message)}`:undefined}>Trimite întrebarea prin e-mail ↗</a><small>Acesta este un ghid local, nu un agent AI conectat și nu trimite notificări automat.</small></section>
 </aside>}
